//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRB.Lib.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Address
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        [DisplayName("Street Name")]
        public string Street { get; set; }
        [DisplayName("City")]
        public string City { get; set; }
        [DisplayName("State")]
        public string State { get; set; }
        [DisplayName("PMB Number")]
        public string PMBNo { get; set; }
        [DisplayName("Town")]
        public string Town { get; set; }
        [DisplayName("LGA")]
        public string LGA { get; set; }

        public string AddressType { get; set; }

        public virtual Citizen Citizen { get; set; }
        public virtual Property Property { get; set; }
        public virtual Party Party { get; set; }

        public override string ToString()
        {
            string result = "";
            result += Street == null ? "" : Street + " ";
            result += Town == null ? "" : Town + " ";
            result += LGA == null ? "" : LGA + " ";
            result += State == null ? "" : State + " ";
            return result;
        }
    }

    public partial class PhoneNumber
    {
        [DisplayName("Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string number { get; set; }
    }
}
