//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRB.Lib.Domain
{
    using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
    
    public partial class Party
    {
        public Party()
        {
            this.gender = "Female";
            this.Addresses = new HashSet<Address>();
        }

        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [DisplayName("Surname")]
        [Required(ErrorMessage = "Surname is required")]
        public string surname { get; set; }

        [DisplayName("First name")]
        [Required(ErrorMessage = "First name is required")]
        public string first_name { get; set; }

        [DisplayName("Middle name")]
        public string middle_name { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage="Gender is Required")]
        public string gender { get; set; }

        [DisplayName("Date of Birth")]
        [Required(ErrorMessage="Date of Birth is required")]
        public Nullable<System.DateTime> dob { get; set; }

        [DisplayName("State of Origin")]
        [Required(ErrorMessage="Please choose a state of origin")]
        public string state_of_origin { get; set; }

        [DisplayName("Home Town")]
        public string home_town { get; set; }

        [DisplayName("Local Government Area")]
        public string lga { get; set; }

        [DisplayName("Corporate Name(If Registering for an organization)")]
        public string OfficeNo { get; set; }

        [DisplayName("Mobile Phone Number")]
        [Required(ErrorMessage = "Phone Number is required")]
        public string MobileNo { get; set; }

        [DisplayName("Home Telephone")]
        public string telephone { get; set; }

        [DisplayName("Email Address")]
        [Required(ErrorMessage = "Please enter a valid email address")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string email { get; set; }

        [ScaffoldColumn(false)]
        public string PartyType { get; set; }

        [DisplayName("Organization Name")]
        public string corporate_name { get; set; }

        [DisplayName("Occupation")]
        public string occupation { get; set; }

        [DisplayName("Name of Previous or Current Employer")]
        public string employer_name { get; set; }

        [DisplayName("Address of The Employer Named Above")]
        public string employer_address { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Application Application { get; set; }


        public string FullName
        {
            get
            {
                return first_name + ", " + surname;
            }
        }
    }
}
