//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRB.Lib.Domain
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Party
    {
        public Party()
        {
            this.Gender = "Female";
            this.Addresses = new List<Address>();
            this.Addresses.Add(new Address()
            {
                AddressType = "ContactAddress"
            });
        }

        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [DisplayName("Surname")]
        [Required(ErrorMessage = "Surname is required")]
        public string Surname { get; set; }

        [DisplayName("First name")]
        [Required(ErrorMessage = "First name is required")]
        public string Firstname { get; set; }

        [DisplayName("Middle name")]
        public string Middlename { get; set; }

        [DisplayName("Gender")]
        public string Gender { get; set; }

        [DisplayName("Date of Birth")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOB { get; set; }

        [DisplayName("State of Origin")]
        public string StateofOrigin { get; set; }

        [DisplayName("Home town")]
        public string HomeTown { get; set; }

        [DisplayName("Local Government Area of Applicant")]
        public string LGA { get; set; }

        [DisplayName("Office Number(If Registering for an organization)")]
        public string OfficeNo { get; set; }

        public Address ContactAddress
        {
            get
            {
                return this.Addresses.Where(p => p.AddressType == "ContactAddress").FirstOrDefault();                
            }
        }


        [DisplayName("Mobile / GSM Number")]
        [Required(ErrorMessage = "Phone Number is required")]
        public String MobileNo { get; set; }

        [DisplayName("Phone 2")]
        public String Phone2 { get; set; }

        [DisplayName("Phone 3")]
        public String Phone3 { get; set; }

        [DisplayName("Email Address")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email Address is required")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }

        [ScaffoldColumn(false)]
        public string PartyType { get; set; }

        [DisplayName("Organization Name")]
        public string OrganizationName { get; set; }

        [DisplayName("Occupation of Applicant")]
        public string Occupation { get; set; }

        [DisplayName("Name of Previous or Current Employer")]
        public string EmployerName { get; set; }

        [DisplayName("Address of The Employer Named Above")]
        public string EmployerAddress { get; set; }

        public virtual List<Address> Addresses { get; set; }

        //[ForeignKey("Application")]


        [DisplayName("Street Name")]
        public string Street { get; set; }
        [DisplayName("State")]
        public string IState { get; set; }
        [DisplayName("Town")]
        public string Town { get; set; }
        [DisplayName("LGA")]
        public string ILGA { get; set; }

        public Application Application { get; set; }


        public string FullName
        {
            get
            {
                return Firstname + ", " + Surname;
            }
        }

    }
}
