//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRB.Lib.Domain
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Property
    {
        public Property()
        {
            this.Addresses = new List<Address>();
            this.Addresses.Add(new Address() { AddressType = "PropertyLocation" });
        }

        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [DisplayName("Development on land")]
        [Required(ErrorMessage = "Please State pogress of development on the land")]
        public String Development { get; set; }

        [DisplayName("In what capacity do you own the property")]
        [Required(ErrorMessage = "Please State what capacity you own the Property")]
        public string CapacityofOwnership { get; set; }

        [DisplayName("What is this use of this property")]
        [Required(ErrorMessage = "Please State what the land is to be used for")]
        public string LandUse { get; set; }

        [DisplayName("How long has this property been in your possession")]
        [Required(ErrorMessage = "State Years")]
        public string PeriodofPossession_years { get; set; }

        [DisplayName("How long has this property been in your possession")]
        [Required(ErrorMessage = "State Months")]
        public string PeriodofPossession_months { get; set; }

        [DisplayName("Approximate size of property")]
        [Required(ErrorMessage = "Please State the approximate area of the property in question")]
        public Nullable<decimal> LandSize { get; set; }

        [DisplayName("unit")]
        [Required(ErrorMessage = "PleaseSpecify Land Unit")]
        public string LandSizeUnit { get; set; }

        [DisplayName("Street Name")]
        public string Street { get; set; }
        [DisplayName("State")]
        public string State { get; set; }
        [DisplayName("Town")]
        public string Town { get; set; }
        [DisplayName("LGA")]
        public string LGA { get; set; }

        [NotMapped]
        public Address PropertyAddress { get; set; }

        public Address getPropertyAddress()
        {
            return this.Addresses.Where(p => p.AddressType == "PropertyLocation").FirstOrDefault();
        }

        public List<Address> Addresses { get; set; }
        public Application Application { get; set; }
    }
}
