//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRB.Lib.Domain
{
    using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
    
    public partial class Property
    {
        public Property()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [DisplayName("Is the Property Developed")]
        [Required(ErrorMessage="Please State whether the Property is Developed or Not")]
        public Nullable<bool> Developed { get; set; }

        [DisplayName("In what capacity do you own the property")]
        [Required(ErrorMessage = "Please State what capacity you own the Property")]
        public string CapacityofOwnership { get; set; }

        [DisplayName("What is this use of this property")]
        [Required(ErrorMessage = "Please State what the land is to be used for")]
        public string LandUse { get; set; }

        [DisplayName("How long has this property been in your possession")]
        [Required(ErrorMessage = "Please State how long this property has been in your possession")]
        public string PeriodofPossession { get; set; }

        [DisplayName("What is the Approximate area of the Property")]
        [Required(ErrorMessage = "Please State the approximate area of the property in question")]
        public Nullable<decimal> ApproximateArea { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Application Application { get; set; }
    }
}
