var hide_empty_list=true;

addListGroup("country", "state");

addList("state", "Select State","", "dummy-states", 1);
addList("state", "FCT", "FCT", "FCT");
addList("state", "Abia", "Abia", "Abia");
addList("state", "Adamawa", "Adamawa", "Adamawa");
addList("state", "Akwa Ibom", "Akwa Ibom", "Akwa Ibom");
addList("state", "Anambra", "Anambra", "Anambra");
addList("state", "Bauchi", "Bauchi", "Bauchi");
addList("state", "Bayelsa", "Bayelsa", "Bayelsa");
addList("state", "Benue", "Benue", "Benue");
addList("state", "Bornu", "Bornu", "Bornu");
addList("state", "Cross River", "Cross River", "Cross River");
addList("state", "Delta", "Delta", "Delta");
addList("state", "Ebonyi ", "Ebonyi ", "Ebonyi ");
addList("state", "Edo", "Edo", "Edo");
addList("state", "Ekiti", "Ekiti", "Ekiti");
addList("state", "Enugu", "Enugu", "Enugu");
addList("state", "Gombe", "Gombe", "Gombe");
addList("state", "Imo", "Imo", "Imo");
addList("state", "Jigawa", "Jigawa", "Jigawa");
addList("state", "Kaduna", "Kaduna", "Kaduna");
addList("state", "Kano", "Kano", "Kano");
addList("state", "Katsina", "Katsina", "Katsina");
addList("state", "Kebbi", "Kebbi", "Kebbi");
addList("state", "Kogi", "Kogi", "Kogi");
addList("state", "Kwara", "Kwara", "Kwara");
addList("state", "Lagos", "Lagos", "Lagos");
addList("state", "Nasarawa", "Nasarawa", "Nasarawa");
addList("state", "Niger", "Niger", "Niger");
addList("state", "Ogun", "Ogun", "Ogun");
addList("state", "Ondo", "Ondo", "Ondo");
addList("state", "Osun", "Osun", "Osun");
addList("state", "Oyo", "Oyo", "Oyo");
addList("state", "Plateau", "Plateau", "Plateau");
addList("state", "Rivers", "Rivers", "Rivers");
addList("state", "Sokoto", "Sokoto", "Sokoto");
addList("state", "Taraba", "Taraba", "Taraba");
addList("state", "Yobe", "Yobe", "Yobe");
addList("state", "Zamfara", "Zamfara", "Zamfara");


addList("dummy-states", "Select LGA", "", "dummy-lga");

addOption("dummy-lga", "Not available", "");

addList("Abia", "Select LGA", "", "dummy-state");
addList("FCT", "Select LGA", "", "dummy-state");
addList("Adamawa", "Select LGA", "", "dummy-state");
addList("Akwa Ibom", "Select LGA", "", "dummy-state");
addList("Anambra", "Select LGA", "", "dummy-state");
addList("Bauchi", "Select LGA", "", "dummy-state");
addList("Bayelsa", "Select LGA", "", "dummy-state");
addList("Benue", "Select LGA", "", "dummy-state");
addList("Bornu", "Select LGA", "", "dummy-state");
addList("Cross River", "Select LGA", "", "dummy-state");
addList("Delta", "Select LGA", "", "dummy-state");
addList("Ebonyi ", "Select LGA", "", "dummy-state");
addList("Edo", "Select LGA", "", "dummy-state");
addList("Ekiti", "Select LGA", "", "dummy-state");
addList("Enugu", "Select LGA", "", "dummy-state");
addList("Gombe", "Select LGA", "", "dummy-state");
addList("Imo", "Select LGA", "", "dummy-state");
addList("Jigawa", "Select LGA", "", "dummy-state");
addList("Kaduna", "Select LGA", "", "dummy-state");
addList("Kano", "Select LGA", "", "dummy-state");
addList("Katsina", "Select LGA", "", "dummy-state");
addList("Kebbi", "Select LGA", "", "dummy-state");
addList("Kogi", "Select LGA", "", "dummy-state");
addList("Kwara", "Select LGA", "", "dummy-state");
addList("Lagos", "Select LGA", "", "dummy-state");
addList("Nasarawa", "Select LGA", "", "dummy-state");
addList("Niger", "Select LGA", "", "dummy-state");
addList("Ogun", "Select LGA", "", "dummy-state");
addList("Ondo", "Select LGA", "", "dummy-state");
addList("Osun", "Select LGA", "", "dummy-state");
addList("Oyo", "Select LGA", "", "dummy-state");
addList("Plateau", "Select LGA", "", "dummy-state");
addList("Rivers", "Select LGA", "", "dummy-state");
addList("Sokoto", "Select LGA", "", "dummy-state");
addList("Taraba", "Select LGA", "", "dummy-state");
addList("Yobe", "Select LGA", "", "dummy-state");
addList("Zamfara", "Select LGA", "", "dummy-state");
addList("FCT", "Gwagwalada");
addList("FCT", "Kuje");
addList("FCT", "Abaji");
addList("FCT", "Abuja Municipal");
addList("FCT", "Bwari");
addList("FCT", "Kwali");
addList("Abia", "Aba North");
addList("Abia", "Aba South");
addList("Abia", "Arochukwu");
addList("Abia", "Bende");
addList("Abia", "Ikwuano");
addList("Abia", "Isiala-Ngwa North");
addList("Abia", "Isiala-Ngwa South");
addList("Abia", "Isuikwato");
addList("Abia", "Obi Nwa");
addList("Abia", "Ohafia");
addList("Abia", "Osisioma");
addList("Abia", "Ngwa");
addList("Abia", "Ugwunagbo");
addList("Abia", "Ukwa East");
addList("Abia", "Ukwa West");
addList("Abia", "Umuahia North");
addList("Abia", "Umuahia South");
addList("Abia", "Umu-Neochi");
addList("Adamawa", "Demsa");
addList("Adamawa", "Fufore");
addList("Adamawa", "Ganaye");
addList("Adamawa", "Gireri");
addList("Adamawa", "Gombi");
addList("Adamawa", "Guyuk");
addList("Adamawa", "Hong");
addList("Adamawa", "Jada");
addList("Adamawa", "Lamurde");
addList("Adamawa", "Madagali");
addList("Adamawa", "Maiha");
addList("Adamawa", "Mayo-Belwa");
addList("Adamawa", "Michika");
addList("Adamawa", "Mubi North");
addList("Adamawa", "Mubi South");
addList("Adamawa", "Numan");
addList("Adamawa", "Shelleng");
addList("Adamawa", "Song");
addList("Adamawa", "Toungo");
addList("Adamawa", "Yola North");
addList("Adamawa", "Yola South");
addList("Akwa Ibom", "Abak");
addList("Akwa Ibom", "Eastern Obolo");
addList("Akwa Ibom", "Eket");
addList("Akwa Ibom", "Esit Eket");
addList("Akwa Ibom", "Essien Udim");
addList("Akwa Ibom", "Etim Ekpo");
addList("Akwa Ibom", "Etinan");
addList("Akwa Ibom", "Ibeno");
addList("Akwa Ibom", "Ibesikpo Asutan");
addList("Akwa Ibom", "Ibiono Ibom");
addList("Akwa Ibom", "Ika");
addList("Akwa Ibom", "Ikono");
addList("Akwa Ibom", "Ikot Abasi");
addList("Akwa Ibom", "Ikot Ekpene");
addList("Akwa Ibom", "Ini");
addList("Akwa Ibom", "Itu");
addList("Akwa Ibom", "Mbo");
addList("Akwa Ibom", "Mkpat Enin");
addList("Akwa Ibom", "Nsit Atai");
addList("Akwa Ibom", "Nsit Ibom");
addList("Akwa Ibom", "Nsit Ubium");
addList("Akwa Ibom", "Obot Akara");
addList("Akwa Ibom", "Okobo");
addList("Akwa Ibom", "Onna");
addList("Akwa Ibom", "Oron");
addList("Akwa Ibom", "Oruk Anam");
addList("Akwa Ibom", "Udung Uko");
addList("Akwa Ibom", "Ukanafun");
addList("Akwa Ibom", "Uruan");
addList("Akwa Ibom", "Urue-Offong/Oruko");
addList("Akwa Ibom", "Uyo");
addList("Anambra", "Aguata");
addList("Anambra", "Anambra East");
addList("Anambra", "Anambra West");
addList("Anambra", "Anaocha");
addList("Anambra", "Awka North");
addList("Anambra", "Awka South");
addList("Anambra", "Ayamelum");
addList("Anambra", "Dunukofia");
addList("Anambra", "Ekwusigo");
addList("Anambra", "Idemili North");
addList("Anambra", "Idemili south");
addList("Anambra", "Ihiala");
addList("Anambra", "Njikoka");
addList("Anambra", "Nnewi North");
addList("Anambra", "Nnewi South");
addList("Anambra", "Ogbaru");
addList("Anambra", "Onitsha North");
addList("Anambra", "Onitsha South ");
addList("Anambra", "Orumba North ");
addList("Anambra", "Orumba South ");
addList("Anambra", "Oyi ");
addList("Bauchi", "Alkaleri ");
addList("Bauchi", "Bauchi ");
addList("Bauchi", "Bogoro ");
addList("Bauchi", "Damban ");
addList("Bauchi", "Darazo ");
addList("Bauchi", "Dass ");
addList("Bauchi", "Ganjuwa ");
addList("Bauchi", "Giade ");
addList("Bauchi", "Itas/Gadau ");
addList("Bauchi", "Jama'are ");
addList("Bauchi", "Katagum ");
addList("Bauchi", "Kirfi ");
addList("Bauchi", "Misau ");
addList("Bauchi", "Ningi ");
addList("Bauchi", "Shira ");
addList("Bauchi", "Tafawa-Balewa ");
addList("Bauchi", "Toro ");
addList("Bauchi", "Warji ");
addList("Bauchi", "Zaki ");
addList("Bayelsa", "Brass ");
addList("Bayelsa", "Ekeremor ");
addList("Bayelsa", "Kolokuma/Opokuma ");
addList("Bayelsa", "Nembe ");
addList("Bayelsa", "Ogbia ");
addList("Bayelsa", "Sagbama ");
addList("Bayelsa", "Southern Jaw ");
addList("Bayelsa", "Yenegoa");
addList("Benue", "Ado ");
addList("Benue", "Agatu ");
addList("Benue", "Apa ");
addList("Benue", "Buruku ");
addList("Benue", "Gboko ");
addList("Benue", "Guma ");
addList("Benue", "Gwer East ");
addList("Benue", "Gwer West ");
addList("Benue", "Katsina-Ala ");
addList("Benue", "Konshisha ");
addList("Benue", "Kwande ");
addList("Benue", "Logo ");
addList("Benue", "Makurdi ");
addList("Benue", "Obi ");
addList("Benue", "Ogbadibo ");
addList("Benue", "Oju ");
addList("Benue", "Okpokwu ");
addList("Benue", "Ohimini ");
addList("Benue", "Oturkpo ");
addList("Benue", "Tarka ");
addList("Benue", "Ukum ");
addList("Benue", "Ushongo ");
addList("Benue", "Vandeikya ");
addList("Bornu", " Abadam ");
addList("Bornu", "Askira/Uba ");
addList("Bornu", "Bama ");
addList("Bornu", "Bayo ");
addList("Bornu", "Biu ");
addList("Bornu", "Chibok ");
addList("Bornu", "Damboa ");
addList("Bornu", "Dikwa ");
addList("Bornu", "Gubio ");
addList("Bornu", "Guzamala ");
addList("Bornu", "Gwoza ");
addList("Bornu", "Hawul ");
addList("Bornu", "Jere ");
addList("Bornu", "Kaga ");
addList("Bornu", "Kala/Balge ");
addList("Bornu", "Konduga ");
addList("Bornu", "Kukawa ");
addList("Bornu", "Kwaya Kusar ");
addList("Bornu", "Mafa ");
addList("Bornu", "Magumeri ");
addList("Bornu", "Maiduguri ");
addList("Bornu", "Marte ");
addList("Bornu", "Mobbar ");
addList("Bornu", "Monguno ");
addList("Bornu", "Ngala ");
addList("Bornu", "Nganzai ");
addList("Bornu", "Shani ");
addList("Cross River", "Akpabuyo ");
addList("Cross River", "Odukpani ");
addList("Cross River", "Akamkpa ");
addList("Cross River", "Biase ");
addList("Cross River", "Abi ");
addList("Cross River", "Ikom ");
addList("Cross River", "Yarkur ");
addList("Cross River", "Odubra ");
addList("Cross River", "Boki ");
addList("Cross River", "Ogoja ");
addList("Cross River", "Yala ");
addList("Cross River", "Obanliku ");
addList("Cross River", "Obudu ");
addList("Cross River", "Calabar South ");
addList("Cross River", "Etung ");
addList("Cross River", "Bekwara ");
addList("Cross River", "Bakassi ");
addList("Cross River", "Calabar Municipality");
addList("Delta", "Oshimili ");
addList("Delta", "Aniocha ");
addList("Delta", "Aniocha South ");
addList("Delta", "Ika South ");
addList("Delta", "Ika North-East ");
addList("Delta", "Ndokwa West ");
addList("Delta", "Ndokwa East ");
addList("Delta", "Isoko south ");
addList("Delta", "Isoko North ");
addList("Delta", "Bomadi ");
addList("Delta", "Burutu ");
addList("Delta", "Ughelli South ");
addList("Delta", "Ughelli North ");
addList("Delta", "Ethiope West ");
addList("Delta", "Ethiope East ");
addList("Delta", "Sapele ");
addList("Delta", "Okpe ");
addList("Delta", "Warri North ");
addList("Delta", "Warri South ");
addList("Delta", "Uvwie ");
addList("Delta", "Udu ");
addList("Delta", "Warri Central ");
addList("Delta", "Ukwani ");
addList("Delta", "Oshimili North ");
addList("Delta", "Patani");
addList("Ebonyi ", "Afikpo South ");
addList("Ebonyi ", "Afikpo North ");
addList("Ebonyi ", "Onicha ");
addList("Ebonyi ", "Ohaozara ");
addList("Ebonyi ", "Abakaliki ");
addList("Ebonyi ", "Ishielu ");
addList("Ebonyi ", "lkwo ");
addList("Ebonyi ", "Ezza ");
addList("Ebonyi ", "Ezza South ");
addList("Ebonyi ", "Ohaukwu ");
addList("Ebonyi ", "Ebonyi ");
addList("Ebonyi ", "Ivo ");
addList("Edo", "Esan North-East ");
addList("Edo", "Esan Central ");
addList("Edo", "Esan West ");
addList("Edo", "Egor ");
addList("Edo", "Ukpoba ");
addList("Edo", "Central ");
addList("Edo", "Etsako Central ");
addList("Edo", "Igueben ");
addList("Edo", "Oredo ");
addList("Edo", "Ovia SouthWest ");
addList("Edo", "Ovia South-East ");
addList("Edo", "Orhionwon ");
addList("Edo", "Uhunmwonde ");
addList("Edo", "Etsako East  ");
addList("Edo", "Esan South-East ");
addList("Ekiti", "Ado ");
addList("Ekiti", "Ekiti-East ");
addList("Ekiti", "Ekiti-West  ");
addList("Ekiti", "Emure/Ise/Orun ");
addList("Ekiti", "Ekiti South-West ");
addList("Ekiti", "Ikare ");
addList("Ekiti", "Irepodun ");
addList("Ekiti", "Ijero,  ");
addList("Ekiti", "Ido/Osi ");
addList("Ekiti", "Oye ");
addList("Ekiti", "Ikole ");
addList("Ekiti", "Moba ");
addList("Ekiti", "Gbonyin ");
addList("Ekiti", "Efon ");
addList("Ekiti", "Ise/Orun  ");
addList("Ekiti", "Ilejemeje.");
addList("Enugu", "Enugu South,  ");
addList("Enugu", "Igbo-Eze South ");
addList("Enugu", "Enugu North ");
addList("Enugu", "Nkanu ");
addList("Enugu", "Udi Agwu ");
addList("Enugu", "Oji-River ");
addList("Enugu", "Ezeagu ");
addList("Enugu", "IgboEze North ");
addList("Enugu", "Isi-Uzo ");
addList("Enugu", "Nsukka ");
addList("Enugu", "Igbo-Ekiti ");
addList("Enugu", "Uzo-Uwani ");
addList("Enugu", "Enugu Eas ");
addList("Enugu", "Aninri ");
addList("Enugu", "Nkanu East ");
addList("Enugu", "Udenu. ");
addList("Gombe", "Akko ");
addList("Gombe", "Balanga ");
addList("Gombe", "Billiri ");
addList("Gombe", "Dukku ");
addList("Gombe", "Kaltungo ");
addList("Gombe", "Kwami ");
addList("Gombe", "Shomgom ");
addList("Gombe", "Funakaye ");
addList("Gombe", "Gombe ");
addList("Gombe", "Nafada/Bajoga  ");
addList("Gombe", "Yamaltu/Delta");
addList("Imo", "Aboh-Mbaise ");
addList("Imo", "Ahiazu-Mbaise ");
addList("Imo", "Ehime-Mbano ");
addList("Imo", "Ezinihitte ");
addList("Imo", "Ideato North ");
addList("Imo", "Ideato South ");
addList("Imo", "Ihitte/Uboma ");
addList("Imo", "Ikeduru ");
addList("Imo", "Isiala Mbano ");
addList("Imo", "Isu ");
addList("Imo", "Mbaitoli ");
addList("Imo", "Mbaitoli ");
addList("Imo", "Ngor-Okpala ");
addList("Imo", "Njaba ");
addList("Imo", "Nwangele ");
addList("Imo", "Nkwerre ");
addList("Imo", "Obowo ");
addList("Imo", "Oguta ");
addList("Imo", "Ohaji/Egbema ");
addList("Imo", "Okigwe ");
addList("Imo", "Orlu ");
addList("Imo", "Orsu ");
addList("Imo", "Oru East ");
addList("Imo", "Oru West ");
addList("Imo", "Owerri-Municipal ");
addList("Imo", "Owerri North ");
addList("Imo", "Owerri West ");
addList("Jigawa", "Auyo ");
addList("Jigawa", "Babura ");
addList("Jigawa", "Birni Kudu ");
addList("Jigawa", "Biriniwa ");
addList("Jigawa", "Buji ");
addList("Jigawa", "Dutse ");
addList("Jigawa", "Gagarawa ");
addList("Jigawa", "Garki ");
addList("Jigawa", "Gumel ");
addList("Jigawa", "Guri ");
addList("Jigawa", "Gwaram ");
addList("Jigawa", "Gwiwa ");
addList("Jigawa", "Hadejia ");
addList("Jigawa", "Jahun ");
addList("Jigawa", "Kafin Hausa ");
addList("Jigawa", "Kaugama Kazaure ");
addList("Jigawa", "Kiri Kasamma ");
addList("Jigawa", "Kiyawa ");
addList("Jigawa", "Maigatari ");
addList("Jigawa", "Malam Madori ");
addList("Jigawa", "Miga ");
addList("Jigawa", "Ringim ");
addList("Jigawa", "Roni ");
addList("Jigawa", "Sule-Tankarkar ");
addList("Jigawa", "Taura  ");
addList("Jigawa", "Yankwashi ");
addList("Kaduna", "Birni-Gwari ");
addList("Kaduna", "Chikun ");
addList("Kaduna", "Giwa ");
addList("Kaduna", "Igabi ");
addList("Kaduna", "Ikara ");
addList("Kaduna", "Jaba ");
addList("Kaduna", "Jema'a ");
addList("Kaduna", "Kachia ");
addList("Kaduna", "Kaduna North ");
addList("Kaduna", "Kaduna South ");
addList("Kaduna", "Kagarko ");
addList("Kaduna", "Kajuru ");
addList("Kaduna", "Kaura ");
addList("Kaduna", "Kauru ");
addList("Kaduna", "Kubau ");
addList("Kaduna", "Kudan ");
addList("Kaduna", "Lere ");
addList("Kaduna", "Makarfi ");
addList("Kaduna", "Sabon-Gari ");
addList("Kaduna", "Sanga ");
addList("Kaduna", "Soba ");
addList("Kaduna", "Zango-Kataf ");
addList("Kaduna", "Zaria ");
addList("Kano", "Ajingi ");
addList("Kano", "Albasu ");
addList("Kano", "Bagwai ");
addList("Kano", "Bebeji ");
addList("Kano", "Bichi ");
addList("Kano", "Bunkure ");
addList("Kano", "Dala ");
addList("Kano", "Dambatta ");
addList("Kano", "Dawakin Kudu ");
addList("Kano", "Dawakin Tofa ");
addList("Kano", "Doguwa ");
addList("Kano", "Fagge ");
addList("Kano", "Gabasawa ");
addList("Kano", "Garko ");
addList("Kano", "Garum ");
addList("Kano", "Mallam ");
addList("Kano", "Gaya ");
addList("Kano", "Gezawa ");
addList("Kano", "Gwale ");
addList("Kano", "Gwarzo ");
addList("Kano", "Kabo ");
addList("Kano", "Kano Municipal ");
addList("Kano", "Karaye ");
addList("Kano", "Kibiya ");
addList("Kano", "Kiru ");
addList("Kano", "kumbotso ");
addList("Kano", "Kunchi ");
addList("Kano", "Kura ");
addList("Kano", "Madobi ");
addList("Kano", "Makoda ");
addList("Kano", "Minjibir ");
addList("Kano", "Nasarawa ");
addList("Kano", "Rano ");
addList("Kano", "Rimin Gado ");
addList("Kano", "Rogo ");
addList("Kano", "Shanono ");
addList("Kano", "Sumaila ");
addList("Kano", "Takali ");
addList("Kano", "Tarauni ");
addList("Kano", "Tofa ");
addList("Kano", "Tsanyawa ");
addList("Kano", "Tudun Wada ");
addList("Kano", "Ungogo ");
addList("Kano", "Warawa ");
addList("Kano", "Wudil");
addList("Katsina", "Bakori ");
addList("Katsina", "Batagarawa ");
addList("Katsina", "Batsari ");
addList("Katsina", "Baure ");
addList("Katsina", "Bindawa ");
addList("Katsina", "Charanchi ");
addList("Katsina", "Dandume ");
addList("Katsina", "Danja ");
addList("Katsina", "Dan Musa ");
addList("Katsina", "Daura ");
addList("Katsina", "Dutsi ");
addList("Katsina", "Dutsin-Ma ");
addList("Katsina", "Faskari ");
addList("Katsina", "Funtua ");
addList("Katsina", "Ingawa ");
addList("Katsina", "Jibia ");
addList("Katsina", "Kafur ");
addList("Katsina", "Kaita ");
addList("Katsina", "Kankara ");
addList("Katsina", "Kankia ");
addList("Katsina", "Katsina ");
addList("Katsina", "Kurfi ");
addList("Katsina", "Kusada ");
addList("Katsina", "Mai'Adua ");
addList("Katsina", "Malumfashi ");
addList("Katsina", "Mani ");
addList("Katsina", "Mashi ");
addList("Katsina", "Matazuu ");
addList("Katsina", "Musawa ");
addList("Katsina", "Rimi ");
addList("Katsina", "Sabuwa ");
addList("Katsina", "Safana ");
addList("Katsina", "Sandamu ");
addList("Katsina", "Zango ");
addList("Kebbi", "Aleiro ");
addList("Kebbi", "Arewa-Dandi ");
addList("Kebbi", "Argungu ");
addList("Kebbi", "Augie ");
addList("Kebbi", "Bagudo ");
addList("Kebbi", "Birnin Kebbi ");
addList("Kebbi", "Bunza ");
addList("Kebbi", "Dandi  ");
addList("Kebbi", "Fakai ");
addList("Kebbi", "Gwandu ");
addList("Kebbi", "Jega ");
addList("Kebbi", "Kalgo  ");
addList("Kebbi", "Koko/Besse ");
addList("Kebbi", "Maiyama ");
addList("Kebbi", "Ngaski ");
addList("Kebbi", "Sakaba ");
addList("Kebbi", "Shanga ");
addList("Kebbi", "Suru ");
addList("Kebbi", "Wasagu/Danko ");
addList("Kebbi", "Yauri ");
addList("Kebbi", "Zuru ");
addList("Kogi", "Adavi ");
addList("Kogi", "Ajaokuta ");
addList("Kogi", "Ankpa ");
addList("Kogi", "Bassa ");
addList("Kogi", "Dekina ");
addList("Kogi", "Ibaji ");
addList("Kogi", "Idah ");
addList("Kogi", "Igalamela-Odolu ");
addList("Kogi", "Ijumu ");
addList("Kogi", "Kabba/Bunu ");
addList("Kogi", "Kogi ");
addList("Kogi", "Lokoja ");
addList("Kogi", "Mopa-Muro ");
addList("Kogi", "Ofu ");
addList("Kogi", "Ogori/Mangongo ");
addList("Kogi", "Okehi ");
addList("Kogi", "Okene ");
addList("Kogi", "Olamabolo ");
addList("Kogi", "Omala ");
addList("Kogi", "Yagba East  ");
addList("Kogi", "Yagba West");
addList("Kwara", "Asa ");
addList("Kwara", "Baruten ");
addList("Kwara", "Edu ");
addList("Kwara", "Ekiti ");
addList("Kwara", "Ifelodun ");
addList("Kwara", "Ilorin East ");
addList("Kwara", "Ilorin West ");
addList("Kwara", "Irepodun ");
addList("Kwara", "Isin ");
addList("Kwara", "Kaiama ");
addList("Kwara", "Moro ");
addList("Kwara", "Offa ");
addList("Kwara", "Oke-Ero ");
addList("Kwara", "Oyun ");
addList("Kwara", "Pategi ");
addList("Lagos", "Agege ");
addList("Lagos", "Ajeromi-Ifelodun ");
addList("Lagos", "Alimosho ");
addList("Lagos", "Amuwo-Odofin ");
addList("Lagos", "Apapa ");
addList("Lagos", "Badagry ");
addList("Lagos", "Epe ");
addList("Lagos", "Eti-Osa ");
addList("Lagos", "Ibeju/Lekki ");
addList("Lagos", "Ifako-Ijaye  ");
addList("Lagos", "Ikeja ");
addList("Lagos", "Ikorodu ");
addList("Lagos", "Kosofe ");
addList("Lagos", "Lagos Island ");
addList("Lagos", "Lagos Mainland ");
addList("Lagos", "Mushin ");
addList("Lagos", "Ojo ");
addList("Lagos", "Oshodi-Isolo ");
addList("Lagos", "Shomolu ");
addList("Lagos", "Surulere");
addList("Nasarawa", "Akwanga ");
addList("Nasarawa", "Awe ");
addList("Nasarawa", "Doma ");
addList("Nasarawa", "Karu ");
addList("Nasarawa", "Keana ");
addList("Nasarawa", "Keffi ");
addList("Nasarawa", "Kokona ");
addList("Nasarawa", "Lafia ");
addList("Nasarawa", "Nasarawa ");
addList("Nasarawa", "Nasarawa-Eggon ");
addList("Nasarawa", "Obi ");
addList("Nasarawa", "Toto ");
addList("Nasarawa", "Wamba ");
addList("Niger", "Agaie ");
addList("Niger", "Agwara ");
addList("Niger", "Bida ");
addList("Niger", "Borgu ");
addList("Niger", "Bosso ");
addList("Niger", "Chanchaga ");
addList("Niger", "Edati ");
addList("Niger", "Gbako ");
addList("Niger", "Gurara ");
addList("Niger", "Katcha ");
addList("Niger", "Kontagora  ");
addList("Niger", "Lapai ");
addList("Niger", "Lavun ");
addList("Niger", "Magama ");
addList("Niger", "Mariga ");
addList("Niger", "Mashegu ");
addList("Niger", "Mokwa ");
addList("Niger", "Muya ");
addList("Niger", "Pailoro ");
addList("Niger", "Rafi ");
addList("Niger", "Rijau ");
addList("Niger", "Shiroro ");
addList("Niger", "Suleja ");
addList("Niger", "Tafa ");
addList("Niger", "Wushishi");
addList("Ogun", "Abeokuta North ");
addList("Ogun", "Abeokuta South ");
addList("Ogun", "Ado-Odo/Ota ");
addList("Ogun", "Egbado North ");
addList("Ogun", "Egbado South ");
addList("Ogun", "Ewekoro ");
addList("Ogun", "Ifo ");
addList("Ogun", "Ijebu East ");
addList("Ogun", "Ijebu North ");
addList("Ogun", "Ijebu North East ");
addList("Ogun", "Ijebu Ode ");
addList("Ogun", "Ikenne ");
addList("Ogun", "Imeko-Afon ");
addList("Ogun", "Ipokia ");
addList("Ogun", "Obafemi-Owode ");
addList("Ogun", "Ogun Waterside ");
addList("Ogun", "Odeda ");
addList("Ogun", "Odogbolu ");
addList("Ogun", "Remo North ");
addList("Ogun", "Shagamu");
addList("Ondo", "Akoko North East ");
addList("Ondo", "Akoko North West ");
addList("Ondo", "Akoko South Akure East ");
addList("Ondo", "Akoko South West ");
addList("Ondo", "Akure North ");
addList("Ondo", "Akure South ");
addList("Ondo", "Ese-Odo ");
addList("Ondo", "Idanre ");
addList("Ondo", "Ifedore ");
addList("Ondo", "Ilaje ");
addList("Ondo", "Ile-Oluji ");
addList("Ondo", "Okeigbo ");
addList("Ondo", "Irele ");
addList("Ondo", "Odigbo ");
addList("Ondo", "Okitipupa ");
addList("Ondo", "Ondo East ");
addList("Ondo", "Ondo West ");
addList("Ondo", "Ose ");
addList("Ondo", "Owo ");
addList("Osun", "Aiyedade ");
addList("Osun", "Aiyedire ");
addList("Osun", "Atakumosa East ");
addList("Osun", "Atakumosa West ");
addList("Osun", "Boluwaduro ");
addList("Osun", "Boripe ");
addList("Osun", "Ede North ");
addList("Osun", "Ede South ");
addList("Osun", "Egbedore ");
addList("Osun", "Ejigbo ");
addList("Osun", "Ife Central ");
addList("Osun", "Ife East ");
addList("Osun", "Ife North ");
addList("Osun", "Ife South ");
addList("Osun", "Ifedayo ");
addList("Osun", "Ifelodun ");
addList("Osun", "Ila ");
addList("Osun", "Ilesha East ");
addList("Osun", "Ilesha West ");
addList("Osun", "Irepodun ");
addList("Osun", "Irewole ");
addList("Osun", "Isokan ");
addList("Osun", "Iwo ");
addList("Osun", "Obokun ");
addList("Osun", "Odo-Otin ");
addList("Osun", "Ola-Oluwa ");
addList("Osun", "Olorunda ");
addList("Osun", "Oriade ");
addList("Osun", "Orolu ");
addList("Osun", "Osogbo");
addList("Oyo", "Afijio ");
addList("Oyo", "Akinyele ");
addList("Oyo", "Atiba ");
addList("Oyo", "Atigbo ");
addList("Oyo", "Egbeda ");
addList("Oyo", "IbadanCentral ");
addList("Oyo", "Ibadan North ");
addList("Oyo", "Ibadan North West ");
addList("Oyo", "Ibadan South East ");
addList("Oyo", "Ibadan South West ");
addList("Oyo", "Ibarapa Central ");
addList("Oyo", "Ibarapa East ");
addList("Oyo", "Ibarapa North ");
addList("Oyo", "Ido ");
addList("Oyo", "Irepo ");
addList("Oyo", "Iseyin ");
addList("Oyo", "Itesiwaju ");
addList("Oyo", "Iwajowa ");
addList("Oyo", "Kajola ");
addList("Oyo", "Lagelu Ogbomosho North ");
addList("Oyo", "Ogbmosho South ");
addList("Oyo", "Ogo Oluwa ");
addList("Oyo", "Olorunsogo ");
addList("Oyo", "Oluyole ");
addList("Oyo", "Ona-Ara ");
addList("Oyo", "Orelope ");
addList("Oyo", "Ori Ire ");
addList("Oyo", "Oyo East ");
addList("Oyo", "Oyo West ");
addList("Oyo", "Saki East ");
addList("Oyo", "Saki West ");
addList("Oyo", "Surulere");
addList("Plateau", "Barikin Ladi ");
addList("Plateau", "Bassa ");
addList("Plateau", "Bokkos ");
addList("Plateau", "Jos East ");
addList("Plateau", "Jos North ");
addList("Plateau", "Jos South ");
addList("Plateau", "Kanam ");
addList("Plateau", "Kanke ");
addList("Plateau", "Langtang North ");
addList("Plateau", "Langtang South ");
addList("Plateau", "Mangu ");
addList("Plateau", "Mikang ");
addList("Plateau", "Pankshin ");
addList("Plateau", "Qua'an Pan ");
addList("Plateau", "Riyom ");
addList("Plateau", "Shendam ");
addList("Plateau", "Wase");
addList("Rivers", "Abua/Odual ");
addList("Rivers", "Ahoada East ");
addList("Rivers", "Ahoada West ");
addList("Rivers", "Akuku Toru ");
addList("Rivers", "Andoni ");
addList("Rivers", "Asari-Toru ");
addList("Rivers", "Bonny ");
addList("Rivers", "Degema ");
addList("Rivers", "Emohua ");
addList("Rivers", "Eleme ");
addList("Rivers", "Etche ");
addList("Rivers", "Gokana ");
addList("Rivers", "Ikwerre ");
addList("Rivers", "Khana ");
addList("Rivers", "Obia/Akpor ");
addList("Rivers", "Ogba/Egbema/Ndoni ");
addList("Rivers", "Ogu/Bolo ");
addList("Rivers", "Okrika ");
addList("Rivers", "Omumma ");
addList("Rivers", "Opobo/Nkoro ");
addList("Rivers", "Oyigbo ");
addList("Rivers", "Port-Harcourt ");
addList("Rivers", "Tai ");
addList("Sokoto", "Binji ");
addList("Sokoto", "Bodinga ");
addList("Sokoto", "Dange-shnsi ");
addList("Sokoto", "Gada ");
addList("Sokoto", "Goronyo ");
addList("Sokoto", "Gudu ");
addList("Sokoto", "Gawabawa ");
addList("Sokoto", "Illela ");
addList("Sokoto", "Isa ");
addList("Sokoto", "Kware ");
addList("Sokoto", "kebbe ");
addList("Sokoto", "Rabah ");
addList("Sokoto", "Sabon birni ");
addList("Sokoto", "Shagari ");
addList("Sokoto", "Silame ");
addList("Sokoto", "Sokoto North ");
addList("Sokoto", "Sokoto South ");
addList("Sokoto", "Tambuwal ");
addList("Sokoto", "Tqngaza ");
addList("Sokoto", "Tureta ");
addList("Sokoto", "Wamako ");
addList("Sokoto", "Wurno ");
addList("Sokoto", "Yabo");
addList("Taraba", "Ardo-kola ");
addList("Taraba", "Bali ");
addList("Taraba", "Donga ");
addList("Taraba", "Gashaka ");
addList("Taraba", "Cassol ");
addList("Taraba", "Ibi ");
addList("Taraba", "Jalingo ");
addList("Taraba", "Karin-Lamido ");
addList("Taraba", "Kurmi ");
addList("Taraba", "Lau ");
addList("Taraba", "Sardauna ");
addList("Taraba", "Takum ");
addList("Taraba", "Ussa ");
addList("Taraba", "Wukari ");
addList("Taraba", "Yorro ");
addList("Taraba", "Zing");
addList("Yobe", "Bade ");
addList("Yobe", "Bursari ");
addList("Yobe", "Damaturu ");
addList("Yobe", "Fika ");
addList("Yobe", "Fune ");
addList("Yobe", "Geidam ");
addList("Yobe", "Gujba ");
addList("Yobe", "Gulani ");
addList("Yobe", "Jakusko ");
addList("Yobe", "Karasuwa ");
addList("Yobe", "Karawa ");
addList("Yobe", "Machina ");
addList("Yobe", "Nangere ");
addList("Yobe", "Nguru Potiskum ");
addList("Yobe", "Tarmua ");
addList("Yobe", "Yunusari ");
addList("Yobe", "Yusufari");
addList("Zamfara", "Anka  ");
addList("Zamfara", "Bakura ");
addList("Zamfara", "Birnin Magaji ");
addList("Zamfara", "Bukkuyum ");
addList("Zamfara", "Bungudu ");
addList("Zamfara", "Gummi ");
addList("Zamfara", "Gusau ");
addList("Zamfara", "Kaura ");
addList("Zamfara", "Namoda ");
addList("Zamfara", "Maradun ");
addList("Zamfara", "Maru ");
addList("Zamfara", "Shinkafi ");
addList("Zamfara", "Talata Mafara ");
addList("Zamfara", "Tsafe ");
addList("Zamfara", "Zurmi");