//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRBMvc.Areas.earchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandOwner
    {
        public int Id { get; set; }
        public string typeofownership { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string surname { get; set; }
        public string title { get; set; }
        public string sex { get; set; }
        public string industryname { get; set; }
        public int Property_Id { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
