//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRBMvc.Areas.earchive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string prkno { get; set; }
        public string prkstatus { get; set; }
        public string typeofownership { get; set; }
        public string dot { get; set; }
        public string partyone { get; set; }
        public string partytwo { get; set; }
        public string drv { get; set; }
        public string drn { get; set; }
        public string drp { get; set; }
        public string tt { get; set; }
        public string party_typeone { get; set; }
        public string party_typetwo { get; set; }
        public int Property_Id { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
